# Generated by Django 5.2.14 on 2026-05-14 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_habitacion', models.CharField(blank=True, max_length=20)),
                ('datos_salud', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('pre_inscrito', 'Pre inscrito'), ('pendiente_pago', 'Pendiente pago'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], db_column='status', default='pre_inscrito', max_length=30)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'inscripciones',
                'managed': False,
            },
        ),
    ]
