packages:
  - "apps/*"
  - "services/*"
  - "packages/*"

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true

autoInstallPeers: false

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
  - unrs-resolver

overrides:
  "@esbuild-kit/esm-loader": "npm:tsx@^4.21.0"
  esbuild: "0.27.3"
