# Generated by Django 5.2.14 on 2026-05-16 01:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_id', models.UUIDField(db_index=True)),
                ('tenant_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('attempt_number', models.IntegerField(default=1)),
                ('gateway_response', models.JSONField(default=dict)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_attempts',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_id', models.UUIDField(db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('old_plan_id', models.UUIDField(blank=True, null=True)),
                ('new_plan_id', models.UUIDField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('change_type', models.CharField(choices=[('create', 'Creación'), ('upgrade', 'Upgrade de plan'), ('downgrade', 'Downgrade de plan'), ('renew', 'Renovación automática'), ('cancel', 'Cancelación'), ('reactivate', 'Reactivación'), ('expire', 'Expiración'), ('past_due', 'Pago fallido')], max_length=20)),
                ('changed_by', models.UUIDField(blank=True, null=True)),
                ('proration_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_history',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_payment_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('trialing', 'En prueba'), ('past_due', 'Pago pendiente'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='trialing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tenant_id', 'status'], name='subscriptio_tenant__5476fe_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='subscriptio_status_302dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['subscription_id', 'status'], name='payment_att_subscri_7a8252_idx'),
        ),
    ]
