kind = "web"
previewPath = "/"
title = "TTDMI - Directorio Turístico Perú"
version = "1.0.0"
id = "artifacts/turismo-peru"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24135

[services.development]
run = "pnpm --filter @workspace/turismo-peru run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/turismo-peru", "run", "build" ]
publicDir = "artifacts/turismo-peru/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24135"
BASE_PATH = "/"
