# Generated by Django 5.2.14 on 2026-05-07 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteIaEmbeddingsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('itinerario', 'Itinerario'), ('viaje', 'Viaje')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('model_used', models.CharField(max_length=60)),
                ('dims', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asistente_ia_embeddings_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenteIaLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('traveler_name', models.CharField(max_length=255)),
                ('traveler_email', models.EmailField(max_length=254)),
                ('traveler_msg', models.TextField(blank=True, null=True)),
                ('intent_data', models.JSONField()),
                ('matched_trip_id', models.UUIDField(blank=True, null=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asistente_ia_leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenteIaSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('intent_data', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(default='es', max_length=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'asistente_ia_sessions',
                'managed': False,
            },
        ),
    ]
