# Generated by Django 5.2.14 on 2026-05-11 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente_ia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteTripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(default='Mi viaje a Perú', max_length=255)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('days', models.IntegerField(default=0)),
                ('travelers', models.IntegerField(default=1)),
                ('itinerary', models.JSONField(default=list)),
                ('budget', models.JSONField(blank=True, null=True)),
                ('weather', models.JSONField(blank=True, null=True)),
                ('hotels', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to='asistente_ia.asistenteiasession')),
            ],
            options={
                'db_table': 'asistente_ia_trip_plans',
                'managed': True,
            },
        ),
    ]
