# Generated by Django 5.2.14 on 2026-05-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente_ia', '0002_asistentetripplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistentetripplan',
            name='destination',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
