# Generated by Django 5.2.14 on 2026-05-16 01:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('plan_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tenants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, unique=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('color_primario', models.CharField(default='#1D9E75', max_length=7)),
                ('color_secundario', models.CharField(default='#1a1a2e', max_length=7)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('ruc', models.CharField(blank=True, default='', max_length=20)),
                ('onboarding_step', models.IntegerField(default=1)),
                ('onboarding_completado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_config',
                'managed': True,
            },
        ),
    ]
